#!/bin/bash
#-------------------------------------------------------------------------------
# mkgithub - A tool that link your project to github
#  by Arignir (benjamin.grange@epitech.eu)
#-------------------------------------------------------------------------------

CYAN="\e[0;36m"
GREEN="\033[0;32m"
RED="\033[0;31m"
DEFAULT="\033[00m"

echo -e "$CYAN""Please enter your github username..."
read github_login
echo "And the project's name on github :"
read github_project

echo "Adding github remote..."

git remote remove origin
git remote add origin git@git.epitech.eu:/${USER}/$(basename "$(pwd)")
git remote set-url --add --push origin git@git.epitech.eu:/${USER}/$(basename "$(pwd)")
git remote set-url --add --push origin "git@github.com:$github_login/$github_project.git"

if [ "$?" == "0" ]
then
    echo -e "$GREEN""Done ! Please push your changes on github ! :)"
else
    echo -e "$RED""Can't set the new remote !"
fi
