#!/bin/bash
#-------------------------------------------------------------------------------
# install - Install all the tools in your ~/bin/ dir
#  by Arignir (benjamin.grange@epitech.eu)
#-------------------------------------------------------------------------------

CYAN="\e[0;36m"
DEFAULT="\033[00m"

echo -e "$CYAN""Installing script..."

mkdir -p ~/bin/

rm -f -r ~/bin/template
mkdir -p ~/bin/template
cp -n -r template/* ~/bin/template

cp -n -r blim ~/bin/
cp -n -r github ~/bin/
cp -n -r mkproject ~/bin/
cp -n -r testproject ~/bin/
cp -n -r up ~/bin/
cp -n -r mrclean ~/bin/

echo -e "Done ! Add ~/bin/ to your PATH variable !""$DEFAULT"
