#!/bin/bash
#-------------------------------------------------------------------------------
# install - Install all the tools in your ~/bin/ dir
#  by Arignir (benjamin.grange@epitech.eu)
#-------------------------------------------------------------------------------

CYAN="\e[0;36m"
DEFAULT="\033[00m"

echo -e "$CYAN""Installing scripts..."

mkdir -p ~/bin/

rm -f -r ~/bin/template
mkdir -p ~/bin/template
cp -R template/ ~/bin/

cp -r blim ~/bin/
cp -r github ~/bin/
cp -r mkproject ~/bin/
cp -r testproject ~/bin/
cp -r up ~/bin/
cp -r mrclean ~/bin/

echo -e "Done ! Add ~/bin/ to your PATH variable !""$DEFAULT"
