#!/bin/bash
#-------------------------------------------------------------------------------
# mrclean - A tool that clears all your temp files
#  by Arignir (benjamin.grange@epitech.eu)
#-------------------------------------------------------------------------------


CYAN="\e[0;36m"
DEFAULT="\033[00m"

echo -e "$CYAN""Activating video-projector..."

xrandr --output DP2 --same-as eDP1
xrandr --output DP2 --mode 1600x1200

echo -e "Done !""$DEFAULT"
